# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c5c663f826b863c2dea55fa6cd6e8dbab46dbc38ec948aa8efe605c1a3fd0d3af036bb88d09047acba7d1ff347cddc395ccfe76e73c52e8bec36d3a5cc4af45

test:
  secret_key_base: b7d964589c40ce7f0e355c8c1e03a30a5c81a538c776e91c53cc46e317f07217f4953858ba46f20151a71f5c20c8c2ae0bcca8c58ed2dbda0f5134891143172d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
